version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    volumes:
      - ./client:/app
      - client-mods:/app/node_modules
      - client-next:/app/.next
    ports:
      - 3000:3000
    depends_on: 
      - server
  server:
    build:
        context: ./server
        dockerfile: Dockerfile
    container_name: server
    restart: always
    env_file: 
      - ./server/.env
    volumes:
      - ./server:/app
      - server-mods:/app/node_modules
    ports:
      - 4000:4000
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gensis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: gensis
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "client"

volumes:
  client-mods:
  client-next:
  server-mods:
  pgadmin-data: