version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  server:
    build:
        context: ./server
        dockerfile: Dockerfile
    container_name: server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"