version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    volumes:
      - ./client:/app
      - client-mods:/app/node_modules
      - client-next:/app/.next
    ports:
      - 3000:3000
  server:
    build:
        context: ./server
        dockerfile: Dockerfile
    container_name: server
    restart: always
    volumes:
      - ./server:/app
      - server-mods:/app/node_modules
    ports:
      - 4000:4000

volumes:
  client-mods:
  client-next:
  server-mods: